var Description = new Array(
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  "<p>HI, nice to meet you.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. PellenLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus orci a purus lacinia consectetur. Vestibulum rutrum ex in odio placerat dictum.</p>Follow me<ul class='m-social'><a href='#' ><i class='fa fa-facebook'></i></a><a href='#'><i class='fa fa-instagram'></i></a><a href='#'><i class='fa fa-github'></i></a></ul>",
  );


function redescription(id) {
  var id_code = id.substring(3, id.length)-1
  document.getElementById(id).title = Description[id_code]
}
